### ISSUE TITLE
"StackOverflowError" exception will be throw when regular expressions contain "@"

### ISSUE THREAD

**Issue by w351565056** [bsaltz/greex#11]
error code like this:
GreexGenerator generator = new GreexGenerator("a@1");
Set<String> matches = generator.generateAll();

As far as I know,“@” is not a speacial symbol in regular expressions,so I think "@" can be output as itself,isn't it right? Thank you in advance.

**Comment by bsaltz** [comment]
Greex uses the [dk.brics.automaton package](https://www.brics.dk/automaton/). The exact flavor of regular expression the library supports can be found in the [`RegExp` javadocs](https://www.brics.dk/automaton/doc/index.html?dk/brics/automaton/RegExp.html).

From that document, the `@` character is a special character for matching "any string", which is why you're getting this error. To generate matches containing the `@` character, you can escape it using a backslash, e.g.:

```java
GreexGenerator generator = new GreexGenerator("a\\@1");
List<String> matches = generator.generateAll();
assert matches.size() == 1;
```

This is also noted in the `GreexGenerator` class javadocs:

> Generates matches for a given regular expression. Support for regular expressions is provided by `RegExp` [external link].

Note that all of the non-standard extra special characters from `RegExp` can be escaped with backslashes.
